#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置

---
#开发环境
server:
  port: 80

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

feign:
  hystrix:
    enabled: true # 开启服务熔断器

# 在被监控服务上添加暴露端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

spring:
  profiles: dev #开发环境
  application:
    name:  microservice-consumer
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  #由于microservice-api模块的entity里的实体类依赖了mybatis,导致这里会自动配置DataSource，如果不需要数据库，这里可以exclude掉
    
  rabbitmq: #Spring cloud Bus消息总线组件的rabbitMQ配置（用于动态刷新config和zipkin数据传输）
    host: localhost
    port: 5672
    username: guest
    password: guest    
  zipkin:
    base-url: http://localhost:9411/  # zipkin服务器的地址
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: rabbit  # web 参数 设置使用http的方式传输数据；rabbit参数设置使用rabbitmq的方式传输数据
  sleuth:
#    web:
#      client:
#        enabled: true   #不用设置，意义未知
    sampler:
      probability: 1  # 设置抽样采集率为100%，默认为0.1，即10%  


---
#生产环境
server:
  port: 80

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

feign:
  hystrix:
    enabled: true # 开启服务熔断器

# 在被监控服务上添加暴露端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

spring:
  profiles: prod #生产环境
  application:
    name:  microservice-consumer
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  #由于microservice-api模块的entity里的实体类依赖了mybatis,导致这里会自动配置DataSource，如果不需要数据库，这里可以exclude掉
    
  rabbitmq: #Spring cloud Bus消息总线组件的rabbitMQ配置（用于动态刷新config和zipkin数据传输）
    host: localhost
    port: 5672
    username: guest
    password: guest    
  zipkin:
    base-url: http://localhost:9411/  # zipkin服务器的地址
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: rabbit  # web 参数 设置使用http的方式传输数据；rabbit参数设置使用rabbitmq的方式传输数据
  sleuth:
#    web:
#      client:
#        enabled: true   #不用设置，意义未知
    sampler:
      probability: 1  # 设置抽样采集率为100%，默认为0.1，即10%  
