#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置

---
#开发环境
server:
  port: 80

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

feign:
  hystrix:
    enabled: true # 开启服务熔断器

# 在被监控服务上添加暴露端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

spring:
  profiles: dev #开发环境
  application:
    name:  microservice-consumer
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  #由于microservice-api模块的entity里的实体类依赖了mybatis,导致这里会自动配置DataSource，如果不需要数据库，这里可以exclude掉



---
#生产环境
server:
  port: 80

eureka:
  client:
    registerWithEureka: false # 服务注册，false表示不将本消费者注册到 Eureka 服务器
    fetchRegistry: true # 服务发现，true从 Eureka 服务器中获取注册信息
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/,http://eureka6002.com:6002/eureka/

feign:
  hystrix:
    enabled: true # 开启服务熔断器

# 在被监控服务上添加暴露端点
#management:
#  endpoints:
#    web:
#      exposure:
#        include: hystrix.stream

spring:
  profiles: prod #生产环境
  application:
    name:  microservice-consumer
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration  #由于microservice-api模块的entity里的实体类依赖了mybatis,导致这里会自动配置DataSource，如果不需要数据库，这里可以exclude掉

