#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置

---
# 开发环境
server:
  port: 7001

spring:
  profiles: dev #开发环境
  application:
    name: microservice-zuul-gateway
  rabbitmq: #Spring cloud Bus消息总线组件的rabbitMQ配置（用于动态刷新config和zipkin数据传输）
    host: localhost
    port: 5672
    username: guest
    password: guest    
  zipkin:
    base-url: http://localhost:9411/  # zipkin服务器的地址
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: rabbit  # web 参数 设置使用http的方式传输数据；rabbit参数设置使用rabbitmq的方式传输数据
  sleuth:
#    web:
#      client:
#        enabled: true   #不用设置，意义未知
    sampler:
      probability: 1  # 设置抽样采集率为100%，默认为0.1，即10%      

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      # 单机版 Eureka 服务注册中心
      #defaultZone: http://localhost:6001/eureka
      # 集群版 Eureka 服务注册中心
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true     #访问路径可以显示IP地址

zuul:
  routes:
    provider-user:    # 路由名称，名称任意，路由名称唯一
      path: /api/user/** # 访问路径
      serviceId: microservice-provider # 指定服务ID，会自动从Eureka中找到此服务的ip和端口
      stripPrefix: false # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1

    # 如果多个服务需要经过路由，则同povider-product方式继续添加，例如：
    #provider-order:
      #path: /order/**
      #serviceId: microservice-order
      #stripPrefix: false


---
# 生产环境
server:
  port: 7001

spring:
  profiles: prod #生产环境
  application:
    name: microservice-zuul-gateway
  rabbitmq: #Spring cloud Bus消息总线组件的rabbitMQ配置（用于动态刷新config和zipkin数据传输）
    host: localhost
    port: 5672
    username: guest
    password: guest    
  zipkin:
    base-url: http://localhost:9411/  # zipkin服务器的地址
    # 关闭服务发现，否则Spring Cloud会把zipkin的url当做服务名称
    discoveryClientEnabled: false
    sender:
      type: rabbit  # web 参数 设置使用http的方式传输数据；rabbit参数设置使用rabbitmq的方式传输数据
  sleuth:
#    web:
#      client:
#        enabled: true   #不用设置，意义未知
    sampler:
      probability: 1  # 设置抽样采集率为100%，默认为0.1，即10%      

eureka:
  client:
    registerWithEureka: true # 服务注册开关
    fetchRegistry: true # 服务发现开关
    serviceUrl: # 客户端(服务提供者)注册到哪一个Eureka Server服务注册中心，多个用逗号分隔
      # 单机版 Eureka 服务注册中心
      #defaultZone: http://localhost:6001/eureka
      # 集群版 Eureka 服务注册中心
      defaultZone: http://eureka6001.com:6001/eureka,http://eureka6002.com:6002/eureka
  instance:
    instanceId: ${spring.application.name}:${server.port} # 指定实例ID,就不会显示主机名了
    preferIpAddress: true     #访问路径可以显示IP地址

zuul:
  routes:
    provider-user:    # 路由名称，名称任意，路由名称唯一
      path: /api/user/** # 访问路径
      serviceId: microservice-provider # 指定服务ID，会自动从Eureka中找到此服务的ip和端口
      stripPrefix: false # 代理转发时去掉前缀，false:代理转发时不去掉前缀 例如:为true时请求 /product/get/1，代理转发到/get/1
